name: hangman
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  envied: ^0.5.2
  tmdb_api: ^2.1.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
  - assets/images/tmdb-logo-placeholder.png
  fonts:
  - family: Lato
    fonts:
      - asset: fonts/Lato-Regular.ttf
      - asset: fonts/Lato-Italic.ttf
        style: italic
      - asset: fonts/Lato-Bold.ttf
        weight: 700
